POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NTI3MmExYTkxNzc4MzJkN2U5YjJlNjYiLCJpYXQiOjE2OTcwNjU1MjgsImV4cCI6MTY5NzA2OTEyOH0.KaWIW9h9vwEA147IKKgv04w3VrNEEY-5dl6IQWUh-7k

{
  "title": "TEST_BLOG",
  "author": "test Author",
  "url": "google.com",
  "likes": 5
}
###
GET http://localhost:3003/api/blogs