GET http://localhost:3003/api/blogs/
###
PUT http://localhost:3003/api/blogs/65272ffcfa68f4d46b010dc8
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QyIiwiaWQiOiI2NTI3MmExYTkxNzc4MzJkN2U5YjJlNjYiLCJpYXQiOjE2OTcwNjYwMTksImV4cCI6MTY5NzA2OTYxOX0.nJfECm2pn8EiaXuWwMc4VkIvddKsWq3li3b4nKLb_qo

{
  "title": "Hello World",
  "likes": 15
}